version: 2.1
jobs:
  eslint:
    working_directory: ~/repo
    docker:
      - image: skobka/worklog-reminder-ci:linux
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable

      - run:
          name: ESLint
          command: yarn run lint

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged

  build-linux:
    working_directory: ~/repo
    docker:
      - image: skobka/worklog-reminder-ci:linux
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - run:
          name: Generate Linux packages
          command: yarn run publish --platform=linux

      - store_artifacts:
          path: ~/repo/out/make

  build-win32:
    working_directory: ~/repo
    docker:
      - image: skobka/worklog-reminder-ci:win32
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --immutable

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
            - .yarn/unplugged
      - run:
          name: Generate Windows packages
          command: yarn run publish --platform=win32 --targets=@electron-forge/maker-squirrel

      - store_artifacts:
          path: ~/repo/out/make

workflows:
  version: 2
  check-code:
    jobs:
      - eslint

  build-packages:
    jobs:
      - build-linux:
          filters:
            branches:
              only: master
      - build-win32:
          filters:
            branches:
              only: master
