name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    container: skobka/worklog-reminder-ci-linux:1.0.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Install dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Build packages
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: make --platform=linux
      
      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Packages
          path: |
                out/make
