name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    container: skobka/worklog-reminder-ci-linux:1.0.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Install dependencies
        run: yarn install --immutable

      - name: Build packages
        run: yarn make --platform=linux
      
      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Linux packages
          path: |
                out/make/**/*.deb
                out/make/**/*.rpm
                out/make/**/*.zip

  build-windows:
    runs-on: ubuntu-20.04
    container: skobka/worklog-reminder-ci-win32:1.0.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Install dependencies
        run: yarn install --immutable

      - name: Build packages
        run: mkdir -p /tmp/wr-wine && WINEPREFIX=/tmp/wr-wine yarn run make --platform=win32 --targets=@electron-forge/maker-squirrel
      
      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Windows packages
          path: |
                out/make/**/*.exe
  
  build-macos:
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Install dependencies
        run: yarn install --immutable

      - name: Build packages
        run: yarn make --platform=darwin
      
      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MacOS packages
          path: |
                out/make/**/*.dmh
                out/make/**/*.zip
