name: ES Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-20.04
    container: skobka/worklog-reminder-ci-linux:1.0.0
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository
      - uses: borales/actions-yarn@v3.0.0
        name: yarn install
        with:
          cmd: install
      - uses: borales/actions-yarn@v3.0.0
        name: yarn lint
        with:
          cmd: lint
