name: ES Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-20.04
    container: skobka/worklog-reminder-ci-linux:1.0.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --immutable

      - name: Check code
        run: yarn lint
